// Original procedural audio; no field recordings or network requests.
class Soundscape {
 constructor(){this.ready=false;this.muted=false;this.volume=.55;this.lastStep=0;this.lastReel=0;this.lastBird=0;this.lastSurf=-1}
 start(){if(this.ready){this.ctx.resume().catch(()=>{});return}try{let AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();let c=this.ctx;this.master=c.createGain();this.master.gain.value=this.volume*.42;this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=18000;this.master.connect(this.filter);this.filter.connect(c.destination);this.noise=c.createBuffer(1,c.sampleRate*3,c.sampleRate);let d=this.noise.getChannelData(0),last=0;for(let i=0;i<d.length;i++){last=(last+(Math.random()*2-1)*.08)/1.035;d[i]=last*3}let wind=c.createBufferSource();wind.buffer=this.noise;wind.loop=true;let f=c.createBiquadFilter();f.type='lowpass';f.frequency.value=450;let g=c.createGain();g.gain.value=.12;wind.connect(f);f.connect(g);g.connect(this.master);wind.start();this.engine=c.createOscillator();this.engine.type='sawtooth';this.engine.frequency.value=38;this.engineGain=c.createGain();this.engineGain.gain.value=0;this.engineFilter=c.createBiquadFilter();this.engineFilter.type='lowpass';this.engineFilter.frequency.value=240;this.engine.connect(this.engineFilter);this.engineFilter.connect(this.engineGain);this.engineGain.connect(this.master);this.engine.start();this.ready=true;this.ctx.resume().catch(()=>{})}catch(e){console.warn('Audio unavailable',e)}}
 setMute(v){this.muted=v;if(this.ready)this.master.gain.setTargetAtTime(v?0:this.volume*.42,this.ctx.currentTime,.06)}
 tone(f=400,dur=.12,amp=.1,type='sine',end=null,pan=0){if(!this.ready||this.muted)return;let c=this.ctx,o=c.createOscillator(),g=c.createGain(),p=c.createStereoPanner();o.type=type;o.frequency.setValueAtTime(f,c.currentTime);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(10,end),c.currentTime+dur);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(amp,c.currentTime+.015);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+dur);p.pan.value=clamp(pan,-1,1);o.connect(g);g.connect(p);p.connect(this.master);o.start();o.stop(c.currentTime+dur+.03)}
 hiss(dur=.5,amp=.4,freq=1600,pan=0){if(!this.ready||this.muted)return;let c=this.ctx,s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain(),p=c.createStereoPanner();s.buffer=this.noise;f.type='lowpass';f.frequency.value=freq;p.pan.value=clamp(pan,-1,1);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(amp,c.currentTime+Math.min(.15,dur*.2));g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+dur);s.connect(f);f.connect(g);g.connect(p);p.connect(this.master);s.start();s.stop(c.currentTime+dur+.03)}
 event(name){if(name==='cast'){this.hiss(.36,.33,3400);this.tone(1400,.055,.08,'triangle')}else if(name==='splash'){this.hiss(.75,.65,2100);this.tone(190,.19,.22,'sine',80)}else if(name==='bite')this.tone(650,.17,.23,'sine',430);else if(name==='hook'){this.tone(900,.09,.15,'triangle',300);this.hiss(.15,.24,2800)}else if(name==='snap'){this.hiss(.08,.65,6500);this.tone(450,.09,.16,'sawtooth',70)}else if(name==='catch'){this.hiss(.32,.4,2400);this.tone(360,.2,.18,'sine',420)}else if(name==='coin')this.tone(930,.21,.10,'triangle',1450);else this.tone(550,.06,.045,'triangle')}
 update(s,dt){if(!this.ready)return;let c=this.ctx,t=c.currentTime;this.filter.frequency.setTargetAtTime(s.under?700:16000,t,.18);this.engine.frequency.setTargetAtTime(35+Math.abs(s.speed)*9,t,.15);this.engineGain.gain.setTargetAtTime(s.boating?.09+Math.abs(s.speed)*.025:0,t,.25);let surf=Math.floor(s.time/5.0);if(surf!==this.lastSurf){this.lastSurf=surf;this.hiss(3.6,clamp(1-Math.abs(s.z-shore(s.x))/120,.025,.55),1000,.1)}if(s.time-this.lastBird>8+Math.random()*6){this.lastBird=s.time;this.tone(1700,1.0,.055,'sine',650,Math.sin(s.time))}if(s.moving&&!s.under&&!s.boating&&s.time-this.lastStep>.36){this.lastStep=s.time;this.hiss(.12,s.wood?.19:.11,s.wood?650:2200);if(s.wood)this.tone(96,.10,.09,'triangle',55)}if(s.reeling&&s.time-this.lastReel>.1){this.lastReel=s.time;this.tone(1000,.03,.045,'square',720)}}
}
