'use strict';
// Small, dependency-free WebGL2 renderer. Coordinates: metres, Y up, south +Z.
const TW = {};
const PI=Math.PI, TAU=PI*2, clamp=(x,a,b)=>Math.max(a,Math.min(b,x)), mix=(a,b,t)=>a+(b-a)*t, smooth=(a,b,x)=>{let t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)};
let seed=830147;
function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}
function hash(x,z){let n=Math.sin(x*127.1+z*311.7)*43758.5453;return n-Math.floor(n)}
function noise(x,z){let a=Math.floor(x),b=Math.floor(z),u=x-a,v=z-b;u=u*u*(3-2*u);v=v*v*(3-2*v);return mix(mix(hash(a,b),hash(a+1,b),u),mix(hash(a,b+1),hash(a+1,b+1),u),v)}
function fbm(x,z){return noise(x,z)*.56+noise(x*2.03,z*2.03)*.28+noise(x*4.1,z*4.1)*.12+noise(x*8.2,z*8.2)*.04}
const V={add:(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub:(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],mul:(a,s)=>[a[0]*s,a[1]*s,a[2]*s],dot:(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len:a=>Math.hypot(...a),norm:a=>{let l=Math.hypot(...a)||1;return a.map(x=>x/l)}};
function identity(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}
function mm(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o}
function perspective(fov,aspect,n,f){let s=1/Math.tan(fov/2);return new Float32Array([s/aspect,0,0,0,0,s,0,0,0,0,(f+n)/(n-f),-1,0,0,2*f*n/(n-f),0])}
function lookAt(eye,target,up=[0,1,0]){let z=V.norm(V.sub(eye,target)),x=V.norm(V.cross(up,z)),y=V.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V.dot(x,eye),-V.dot(y,eye),-V.dot(z,eye),1])}
function ortho(l,r,b,t,n,f){return new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1])}
function transform(p,yaw=0,pitch=0,roll=0){let cy=Math.cos(yaw),sy=Math.sin(yaw),cx=Math.cos(pitch),sx=Math.sin(pitch),cz=Math.cos(roll),sz=Math.sin(roll);let a=new Float32Array([cy,0,-sy,0,0,1,0,0,sy,0,cy,0,p[0],p[1],p[2],1]);let b=new Float32Array([cz,sz,0,0,-sz,cz,0,0,0,0,1,0,0,0,0,1]);let c=new Float32Array([1,0,0,0,0,cx,sx,0,0,-sx,cx,0,0,0,0,1]);return mm(mm(a,c),b)}
function apply(m,p){return [m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]]}
function hex(s){s=s.replace('#','');return [0,2,4].map(i=>parseInt(s.slice(i,i+2),16)/255)}
const C={wood:hex('938170'),darkWood:hex('584c3e'),sand:hex('dfd1ac'),white:hex('e9e8df'),steel:hex('647a80'),rope:hex('c1a36a'),leaf:hex('45662c'),bark:hex('8a806a'),rock:hex('555b51')};
class Mesh {
 constructor(){this.v=[];this.count=0;this.model=identity()}
 vert(p,n,c,type=0,uv=[0,0]){this.v.push(...p,...n,...c,type,...uv)}
 tri(a,b,c,color,type=0,normal=null,uvs=null){let n=normal||V.norm(V.cross(V.sub(b,a),V.sub(c,a)));this.vert(a,n,color,type,uvs?uvs[0]:[0,0]);this.vert(b,n,color,type,uvs?uvs[1]:[0,0]);this.vert(c,n,color,type,uvs?uvs[2]:[0,0])}
 quad(a,b,c,d,col,type=0,n=null){this.tri(a,b,c,col,type,n);this.tri(a,c,d,col,type,n)}
 box(p,s,c,type=0,yaw=0){let [x,y,z]=s.map(v=>v/2),m=transform(p,yaw),v=[[-x,-y,-z],[x,-y,-z],[x,y,-z],[-x,y,-z],[-x,-y,z],[x,-y,z],[x,y,z],[-x,y,z]].map(p=>apply(m,p));for(let f of [[0,3,2,1],[4,5,6,7],[0,4,7,3],[1,2,6,5],[3,7,6,2],[0,1,5,4]])this.quad(...f.map(i=>v[i]),c,type)}
 sphere(p,s,c,type=0,seg=12,rings=8){for(let j=0;j<rings;j++)for(let i=0;i<seg;i++){let a=[];for(let [u,v]of [[i,j],[i+1,j],[i+1,j+1],[i,j+1]]){let th=u/seg*TAU,ph=v/rings*PI,n=[Math.sin(ph)*Math.cos(th),Math.cos(ph),Math.sin(ph)*Math.sin(th)];a.push([p.map((x,k)=>x+n[k]*s[k]),V.norm(n.map((x,k)=>x/s[k]))])}for(let idx of [[0,2,1],[0,3,2]])for(let k of idx)this.vert(a[k][0],a[k][1],c,type)}}
 tube(a,b,r,c,type=0,seg=8,r2=r){let d=V.norm(V.sub(b,a)),u=V.norm(V.cross(d,Math.abs(d[1])>.9?[1,0,0]:[0,1,0])),v=V.cross(d,u);for(let i=0;i<seg;i++){let pts=[],ns=[];for(let [t,end,rr]of [[i,0,r],[i+1,0,r],[i+1,1,r2],[i,1,r2]]){let th=t/seg*TAU,n=V.add(V.mul(u,Math.cos(th)),V.mul(v,Math.sin(th)));pts.push(V.add(end?b:a,V.mul(n,rr)));ns.push(n)}for(let idx of [[0,1,2],[0,2,3]])for(let k of idx)this.vert(pts[k],ns[k],c,type);this.tri(a,pts[1],pts[0],c,type,V.mul(d,-1));this.tri(b,pts[3],pts[2],c,type,d)}}
 torus(p,r,t,c,type=0,axis='z',seg=32){for(let i=0;i<seg;i++){let a=i/seg*TAU,b=(i+1)/seg*TAU,pts=axis==='y'?[[p[0]+Math.cos(a)*r,p[1],p[2]+Math.sin(a)*r],[p[0]+Math.cos(b)*r,p[1],p[2]+Math.sin(b)*r]]:[[p[0]+Math.cos(a)*r,p[1]+Math.sin(a)*r,p[2]],[p[0]+Math.cos(b)*r,p[1]+Math.sin(b)*r,p[2]]];this.tube(...pts,t,c,type,6)}}
 append(other,m=identity()){for(let i=0;i<other.v.length;i+=12){let p=apply(m,other.v.slice(i,i+3)),a=other.v.slice(i+3,i+6),n=V.norm([m[0]*a[0]+m[4]*a[1]+m[8]*a[2],m[1]*a[0]+m[5]*a[1]+m[9]*a[2],m[2]*a[0]+m[6]*a[1]+m[10]*a[2]]);this.v.push(...p,...n,...other.v.slice(i+6,i+12))}}
 upload(gl,dynamic=false){if(!this.vao){this.vao=gl.createVertexArray();this.buffer=gl.createBuffer()}gl.bindVertexArray(this.vao);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(this.v),dynamic?gl.DYNAMIC_DRAW:gl.STATIC_DRAW);for(let [loc,size,offset]of [[0,3,0],[1,3,3],[2,3,6],[3,1,9],[4,2,10]]){gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,48,offset*4)}this.count=this.v.length/12;gl.bindVertexArray(null)}
}
function shader(gl,vs,fs){const compile=(type,src)=>{let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s};let p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,vs));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return {p,u:new Map()}}
function uniform(gl,p,name,type,value){let l=p.u.get(name);if(l===undefined){l=gl.getUniformLocation(p.p,name);p.u.set(name,l)}if(l===null)return;if(type==='m')gl.uniformMatrix4fv(l,false,value);else if(type==='3')gl.uniform3fv(l,value);else if(type==='4')gl.uniform4fv(l,value);else if(type==='2')gl.uniform2fv(l,value);else if(type==='i')gl.uniform1i(l,value);else gl.uniform1f(l,value)}
const GLSL_NOISE=`float hash21(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise2(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash21(i),hash21(i+vec2(1,0)),f.x),mix(hash21(i+vec2(0,1)),hash21(i+1.),f.x),f.y);}float fbm2(vec2 p){float f=0.,a=.55;for(int i=0;i<4;i++){f+=noise2(p)*a;p=p*2.03+13.7;a*=.48;}return f;}`;
const GLSL_SKY=`
vec3 skyColor(vec3 d){
 float day=smoothstep(-.15,.16,uSun.y),h=pow(max(0.,1.-max(0.,d.y)),3.);vec3 top=mix(vec3(.005,.011,.027),vec3(.10,.33,.57),day),horizon=mix(vec3(.019,.032,.065),vec3(.66,.79,.84),day);float dusk=exp(-abs(uSun.y)*8.)*smoothstep(-.23,-.04,uSun.y);vec3 c=mix(top,horizon,h);float facing=pow(max(0.,dot(normalize(vec3(uSun.x,.05,uSun.z)),d)),6.);c+=vec3(.78,.22,.055)*dusk*facing*(.4+.6*h);
 float sd=max(0.,dot(d,uSun));c+=vec3(1.,.78,.43)*pow(sd,350.)*day*.32;c+=vec3(3.,2.6,2.2)*smoothstep(.99973,.99990,sd)*step(-.04,uSun.y);float moon=max(0.,dot(d,-uSun));c+=vec3(.48,.59,.7)*smoothstep(.99975,.99986,moon)*(1.-day);
 if(d.y>.025&&uCloud>0.){vec2 q=d.xz/(d.y+.15)*2.5+vec2(uTime*.002,0.);float n=fbm2(q),fine=fbm2(q*3.7);float density=smoothstep(.59-uCloud*.18,.72-uCloud*.17,n+fine*.075);float sunward=fbm2(q+normalize(uSun.xz+vec2(.001))*.25);float shade=clamp(.5+(n-sunward)*3.,0.,1.);vec3 cloud=mix(vec3(.48,.59,.66),vec3(1.,.995,.965),shade);cloud=mix(cloud,vec3(.91,.49,.27),dusk*.6);cloud=mix(vec3(.04,.062,.091),cloud,day);float edges=pow(1.-density,3.)*density*3.;cloud+=vec3(.16,.14,.11)*edges*day;float aerial=smoothstep(.025,.32,d.y);cloud=mix(horizon,cloud,.42+.58*aerial);c=mix(c,cloud,density*aerial*.96);float cirrus=pow(max(0.,sin(d.x*35.+d.z*11.+fine*7.)),12.)*smoothstep(.2,.6,d.y);c=mix(c,mix(vec3(.07,.09,.14),vec3(.87,.9,.9),day),cirrus*.045*uCirrus);}
 if(day<.5&&d.y>0.){vec2 st=floor(d.xz/(d.y+.08)*650.);float stars=step(.998,hash21(st))*pow(hash21(st+9.),8.);c+=stars*(1.-day)*smoothstep(0.,.3,d.y);}return c;}`;
