// Two actual FFT cascades, evolved from a Phillips/Tessendorf spectrum.
// CPU inverse FFT keeps this static/offline build independent of GPU compute.
class FFTSea {
 constructor(gl,N=64,L=64,amplitude=.18){this.gl=gl;this.N=N;this.L=L;this.amp=amplitude;this.h0=new Float32Array(N*N*2);this.re=new Float32Array(N*N);this.im=new Float32Array(N*N);this.data=new Float32Array(N*N*4);this.rowR=new Float32Array(N);this.rowI=new Float32Array(N);this.omega=new Float32Array(N*N);const gauss=()=>Math.sqrt(-2*Math.log(Math.max(1e-8,rnd())))*Math.cos(TAU*rnd());let wind=14,lp=wind*wind/9.81;for(let y=0;y<N;y++)for(let x=0;x<N;x++){let kx=TAU*(x<N/2?x:x-N)/L,kz=TAU*(y<N/2?y:y-N)/L,k2=kx*kx+kz*kz,idx=y*N+x,k=Math.sqrt(k2),w=k?((kx*.82+kz*.57)/k):0,P=k2?Math.exp(-1/(k2*lp*lp))/(k2*k2)*w*w*Math.exp(-k2*.015):0;this.h0[idx*2]=gauss()*Math.sqrt(P*.5);this.h0[idx*2+1]=gauss()*Math.sqrt(P*.5);this.omega[idx]=Math.sqrt(9.81*k)}this.scale=1;this.tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA32F,N,N,0,gl.RGBA,gl.FLOAT,this.data);let linear=gl.getExtension('OES_texture_float_linear');gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,linear?gl.LINEAR:gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,linear?gl.LINEAR:gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);this.update(0,true)}
 ifft(r,i){let n=r.length;for(let a=1,b=0;a<n;a++){let bit=n>>1;for(;b&bit;bit>>=1)b^=bit;b^=bit;if(a<b){[r[a],r[b]]=[r[b],r[a]];[i[a],i[b]]=[i[b],i[a]]}}for(let len=2;len<=n;len<<=1){let th=TAU/len,wr=Math.cos(th),wi=Math.sin(th);for(let start=0;start<n;start+=len){let cr=1,ci=0;for(let j=0;j<len/2;j++){let a=start+j,b=a+len/2,br=r[b]*cr-i[b]*ci,bi=r[b]*ci+i[b]*cr,ar=r[a],ai=i[a];r[a]=ar+br;i[a]=ai+bi;r[b]=ar-br;i[b]=ai-bi;let t=cr*wr-ci*wi;ci=cr*wi+ci*wr;cr=t}}}for(let j=0;j<n;j++){r[j]/=n;i[j]/=n}}
 update(t,normalize=false){let N=this.N,h=this.h0,re=this.re,im=this.im;for(let y=0;y<N;y++)for(let x=0;x<N;x++){let a=y*N+x,b=((N-y)%N)*N+(N-x)%N,ang=this.omega[a]*t,c=Math.cos(ang),s=Math.sin(ang);re[a]=(h[a*2]+h[b*2])*c-(h[a*2+1]+h[b*2+1])*s;im[a]=(h[a*2]-h[b*2])*s+(h[a*2+1]-h[b*2+1])*c}for(let y=0;y<N;y++){this.rowR.set(re.subarray(y*N,(y+1)*N));this.rowI.set(im.subarray(y*N,(y+1)*N));this.ifft(this.rowR,this.rowI);re.set(this.rowR,y*N);im.set(this.rowI,y*N)}for(let x=0;x<N;x++){for(let y=0;y<N;y++){this.rowR[y]=re[y*N+x];this.rowI[y]=im[y*N+x]}this.ifft(this.rowR,this.rowI);for(let y=0;y<N;y++){re[y*N+x]=this.rowR[y];im[y*N+x]=this.rowI[y]}}if(normalize){let rms=Math.sqrt(re.reduce((s,x)=>s+x*x,0)/(N*N));this.scale=this.amp/(rms||1)}let dx=this.L/N;for(let y=0;y<N;y++)for(let x=0;x<N;x++){let a=y*N+x,l=y*N+(x+N-1)%N,r=y*N+(x+1)%N,d=((y+N-1)%N)*N+x,u=((y+1)%N)*N+x;this.data[a*4]=re[a]*this.scale;this.data[a*4+1]=(re[r]-re[l])*this.scale/(2*dx);this.data[a*4+2]=(re[u]-re[d])*this.scale/(2*dx);this.data[a*4+3]=clamp(-(re[l]+re[r]+re[u]+re[d]-4*re[a])*this.scale*.7,0,1)}let gl=this.gl;gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.texSubImage2D(gl.TEXTURE_2D,0,0,0,N,N,gl.RGBA,gl.FLOAT,this.data)}
 height(x,z){let n=this.N,u=((x/this.L%1+1)%1)*n,v=((z/this.L%1+1)%1)*n,a=Math.floor(u),b=Math.floor(v),s=u-a,t=v-b;const h=(x,y)=>this.data[((y%n)*n+x%n)*4];return mix(mix(h(a,b),h(a+1,b),s),mix(h(a,b+1),h(a+1,b+1),s),t)}
}
function shore(x){return mix(-42+.00125*x*x+10*Math.exp(-Math.pow((x-205)/70,2))+16*Math.exp(-Math.pow((x+220)/62,2)),-950,smooth(360,610,Math.abs(x)))}
function ground(x,z){let s=shore(x)-z,edge=smooth(410,650,Math.abs(x));if(s<0||edge>.95){let depth=.3+(-s)*.047+smooth(125,320,z)*24;let reef=Math.exp(-((x+78)**2+(z-58)**2)/2200);return -Math.max(.15,depth-reef*3.5)}let beach=s*.085,hills=smooth(38,160,s);let peak=174*Math.exp(-(x*x/65000+(z+400)**2/75000))+86*Math.exp(-((x+215)**2/6500+(z+185)**2/28000))+82*Math.exp(-((x-225)**2/7200+(z+165)**2/27000));let valley=1-.76*Math.exp(-((x-38)**2/10000+(z+136)**2/17000));return mix(beach,(peak*(.7+fbm(x*.012,z*.012)*.5)+15*fbm(x*.022,z*.022))*valley,hills)*(1-edge)-edge*12}
const GLSL_SHORE=`float shore(float x){return mix(-42.+.00125*x*x+10.*exp(-pow((x-205.)/70.,2.))+16.*exp(-pow((x+220.)/62.,2.)),-950.,smoothstep(360.,610.,abs(x)));}float bed(vec2 p){float d=p.y-shore(p.x);return -max(.15,.3+d*.047+smoothstep(125.,320.,p.y)*24.-exp(-((p.x+78.)*(p.x+78.)+(p.y-58.)*(p.y-58.))/2200.)*3.5);}`;
const OCEAN_VS=`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;uniform mat4 uVP;uniform sampler2D uFFT0,uFFT1;uniform float uTime,uSea,uSwash;out vec3 vWorld;out vec3 vNormal;out float vFoam;${GLSL_SHORE}
void main(){vec2 p=aPos.xz;vec4 a=texture(uFFT0,p/64.),b=texture(uFFT1,p/192.);float depth=max(0.,p.y-shore(p.x))*.047,shallow=smoothstep(0.,2.5,depth);float sw=sin((p.y-shore(p.x))*.24+uTime*1.3+sin(p.x*.03)*.8);float beach=exp(-pow((depth-.65)/1.1,2.))*uSwash;vec3 pos=aPos;pos.y=(a.x+b.x)*shallow*uSea+sw*.27*beach;pos.xz-=vec2(a.y+b.y,a.z+b.z)*.38*shallow;vWorld=pos;vNormal=normalize(vec3(-(a.y+b.y)*uSea,1.,-(a.z+b.z)*uSea-.065*cos((p.y-shore(p.x))*.24+uTime*1.3)*beach));vFoam=a.w+b.w;gl_Position=uVP*vec4(pos,1.);}`;
const OCEAN_FS=`#version 300 es
precision highp float;in vec3 vWorld,vNormal;in float vFoam;out vec4 frag;uniform sampler2D uScene,uDepth,uShadow;uniform vec2 uRes;uniform vec3 uCamera,uSun;uniform mat4 uLightVP;uniform float uTime,uCloud,uCirrus,uSea,uSwash,uHaze;uniform vec4 uWakes[24];${GLSL_NOISE}${GLSL_SKY}${GLSL_SHORE}
float linearDepth(float z){return 2.*.1*4500./(4500.+.1-(z*2.-1.)*(4500.-.1));}
void main(){float shoreDist=vWorld.z-shore(vWorld.x);if(shoreDist< -5.)discard;vec3 n=vNormal;float detailFade=1.-smoothstep(20.,110.,length(vWorld-uCamera));n.x+=sin(vWorld.x*2.7+uTime*1.7+sin(vWorld.z*.7))*.021*uSea*detailFade;n.z+=sin(vWorld.z*3.6-uTime*2.2+sin(vWorld.x*.8))*.019*uSea*detailFade;n=normalize(n);vec3 view=normalize(uCamera-vWorld);bool below=uCamera.y<vWorld.y;if(below)n=-n;vec2 uv=gl_FragCoord.xy/uRes;if(gl_FragCoord.z>texture(uDepth,uv).r)discard;float sceneD=linearDepth(texture(uDepth,uv).r),ownD=linearDepth(gl_FragCoord.z);float thick=max(0.,sceneD-ownD);vec2 offset=n.xz*.016*min(thick*.4,1.);vec2 ru=clamp(uv+offset,vec2(.002),vec2(.998));if(linearDepth(texture(uDepth,ru).r)<ownD)ru=uv;vec3 bg=texture(uScene,ru).rgb;float day=smoothstep(-.15,.16,uSun.y);vec3 absorb=vec3(.18,.055,.024),water=mix(vec3(.005,.045,.09),vec3(.005,.26,.31),exp(-max(0.,-bed(vWorld.xz))*.035))*mix(.15,1.,day);vec3 transmitted=bg*exp(-absorb*thick)+water*(1.-exp(-absorb*thick));float fres=.025+.975*pow(1.-max(0.,dot(n,view)),5.);vec3 reflected=skyColor(reflect(-view,n));float rough=.055+uSea*.014+min(.09,length(vWorld-uCamera)*.00008);vec3 halfv=normalize(uSun+view);float ndh=max(0.,dot(n,halfv)),den=ndh*ndh*(rough*rough-1.)+1.;float spec=min(12.,rough*rough/(3.14159*den*den))*max(0.,uSun.y)*.20;vec3 color=mix(transmitted,reflected,clamp(fres,.025,.91));color+=vec3(1.,.85,.57)*spec*.65;float d=max(0.,shoreDist)*.047,phase=shoreDist*.24+uTime*1.3+sin(vWorld.x*.03)*.8;float foam=(smoothstep(.78,.98,sin(phase))*exp(-pow((d-.7)/1.15,2.))*.83+smoothstep(.14,.42,vFoam)*.4)*uSwash;float lace=fbm2(vWorld.xz*1.8+uTime*.12);foam*=smoothstep(.28,.67,lace);for(int i=0;i<24;i++){vec4 w=uWakes[i];float age=uTime-w.z;if(w.w>0.&&age>=0.&&age<13.){float dist=length(vWorld.xz-w.xy),rad=.8+age*.52;foam+=exp(-pow((dist-rad)/(.4+age*.06),2.))*w.w*(1.-age/13.)*.45;}}vec4 light=uLightVP*vec4(vWorld,1.);vec3 sp=light.xyz/light.w*.5+.5;float shadow=1.;if(all(greaterThan(sp,vec3(0)))&&all(lessThan(sp,vec3(1))))shadow=sp.z-.003>texture(uShadow,sp.xy).r?.64:1.;color*=shadow;foam=clamp(foam,0.,.86);color=mix(color,vec3(.78,.91,.87)*mix(.12,1.,day),foam);float fog=1.-exp(-length(vWorld-uCamera)*(.00020+uHaze*.0004));color=mix(color,skyColor(normalize(vWorld-uCamera)),fog);if(below)color=mix(color,vec3(.015,.24,.27)*mix(.2,1.,day),.42);frag=vec4(color,1.);}`;
