const WORLD_VS=`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;layout(location=1)in vec3 aNormal;layout(location=2)in vec3 aColor;layout(location=3)in float aType;layout(location=4)in vec2 aUV;uniform mat4 uModel,uVP,uLightVP;out vec3 vWorld,vNormal,vColor;out float vType;out vec2 vUV;out vec4 vShadow;
void main(){vec4 p=uModel*vec4(aPos,1.);vWorld=p.xyz;vNormal=mat3(uModel)*aNormal;vColor=aColor;vType=aType;vUV=aUV;vShadow=uLightVP*p;gl_Position=uVP*p;}`;
const WORLD_FS=`#version 300 es
precision highp float;in vec3 vWorld,vNormal,vColor;in float vType;in vec2 vUV;in vec4 vShadow;out vec4 frag;uniform sampler2D uShadow,uAtlas;uniform vec3 uCamera,uSun,uLightDir,uForward;uniform float uTime,uCloud,uCirrus,uHaze,uExposure,uCaustics,uFlash;uniform vec3 uLamps[8];${GLSL_NOISE}${GLSL_SKY}
float shadow(){vec3 p=vShadow.xyz/vShadow.w*.5+.5;if(any(lessThan(p,vec3(0)))||any(greaterThan(p,vec3(1))))return 1.;float bias=.0013+.002*(1.-max(0.,dot(normalize(vNormal),uLightDir))),s=0.;vec2 texel=1./vec2(textureSize(uShadow,0));for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++)s+=p.z-bias>texture(uShadow,p.xy+vec2(x,y)*texel).r?0.:1.;return s/9.;}
void main(){vec3 n=normalize(vNormal),base=vColor;float type=vType;if(type>8.5&&type<9.5){vec2 q=vUV;float canopy=length((q-vec2(.5,.65))/vec2(.49,.35));float edge=noise2(q*29.)*.17+noise2(q*64.)*.055;bool trunk=q.y<.44&&abs(q.x-.5)<.027;if(canopy>1.-edge&&!trunk)discard;if(trunk&&q.y<.34)base=vec3(.30,.26,.19);else{base*=.77+.38*noise2(q*16.);n=normalize(vec3((q.x-.5)*.7,.8, .25));}}float day=smoothstep(-.15,.16,uSun.y),grain=1.;if(type>.5&&type<1.5){float ripple=sin(vWorld.x*4.1+sin(vWorld.z*.24)*3.);grain=.88+noise2(vWorld.xz*19.)*.12+ripple*.028;float wet=1.-smoothstep(.0,.9,vWorld.y);base=mix(base,base*vec3(.55,.64,.63),wet*.8);}else if(type>1.5&&type<2.5){float g=noise2(vec2(vWorld.x*25.+vWorld.z*2.,vWorld.y*2.7+vWorld.z*.13));grain=.91+g*.14;float lines=sin(vWorld.x*110.+noise2(vWorld.xz*.24)*6.);grain*=1.-.024*lines;}else if(type>2.5&&type<3.5){grain=.72+noise2(vWorld.xz*3.+vWorld.y)*.38;}else if(type>3.5&&type<4.5){grain=.6+fbm2(vWorld.xz*1.7+vWorld.y)*.65;}else if(type>4.5&&type<5.5){vec4 t=texture(uAtlas,vUV);base=t.rgb;}else if(type>6.5&&type<7.5){grain=.88+sin(vWorld.x*25.+vWorld.z*21.)*.09;}base*=grain;float sh=shadow(),ndl=max(0.,dot(n,uLightDir));float cloudShadow=mix(1.,.72,smoothstep(.55,.68,fbm2(vWorld.xz*.007+uTime*.002)))*uCloud+(1.-uCloud);vec3 ambient=mix(vec3(.024,.043,.068),vec3(.24,.34,.38),day)*(n.y*.22+.78);vec3 sunlight=mix(vec3(.15,.21,.3),mix(vec3(1.7,.65,.25),vec3(1.34,1.27,1.04),smoothstep(.06,.40,uSun.y)),day);vec3 lit=ambient+sunlight*ndl*sh*cloudShadow;for(int i=0;i<8;i++){vec3 d=uLamps[i]-vWorld;float r=length(d);lit+=vec3(1.5,.82,.3)*max(0.,dot(n,normalize(d)))*10./(3.+r*r)*(1.-day);}if(uFlash>.1){vec3 to=vWorld-uCamera;float cone=smoothstep(.82,.96,dot(normalize(to),uForward));lit+=vec3(.83,.91,.92)*cone*max(0.,dot(n,normalize(-to)))*24./(2.+dot(to,to));}vec3 color=pow(max(base,vec3(.001)),vec3(2.2))*lit;vec3 view=normalize(uCamera-vWorld),h=normalize(view+uLightDir);float spec=pow(max(0.,dot(n,h)),type>6.5?75.:32.)*(type>6.5?.2:.018)*sh*day;color+=vec3(spec);if(vWorld.y<.1&&uCaustics>.1){float ca=pow(max(0.,sin(vWorld.x*2.3+uTime+sin(vWorld.z*2.5-uTime*.8))*sin(vWorld.z*2.4+uTime*.6+sin(vWorld.x*2.9))),12.);color+=base*ca*.40*day*exp(vWorld.y*.06);}if(type>5.5&&type<6.5)color+=base*(1.-day)*2.;color*=uExposure;color=pow(clamp(color/(color+vec3(.65)),0.,1.),vec3(1./2.2));float dist=length(vWorld-uCamera);float waterPath=0.;if(uCamera.y<0.&&vWorld.y<0.)waterPath=dist;else if(vWorld.y<0.)waterPath=dist*clamp(-vWorld.y/(uCamera.y-vWorld.y),0.,1.);else if(uCamera.y<0.)waterPath=dist*clamp(-uCamera.y/(vWorld.y-uCamera.y),0.,1.);color=color*exp(-vec3(.14,.042,.026)*waterPath)+vec3(.012,.18,.21)*mix(.15,1.,day)*(1.-exp(-vec3(.14,.042,.026)*waterPath));float fog=1.-exp(-dist*(.0003+uHaze*.00065));color=mix(color,skyColor(normalize(vWorld-uCamera)),fog);if(type>7.5&&type<8.5){color=mix(color,skyColor(reflect(-view,n)),.4);frag=vec4(color,.19);}else frag=vec4(color,1.);}`;
const QUAD_VS=`#version 300 es
precision highp float;out vec2 vUV;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);vUV=p;gl_Position=vec4(p*2.-1.,0,1);}`;
const SKY_FS=`#version 300 es
precision highp float;in vec2 vUV;out vec4 frag;uniform vec3 uForward,uRight,uUp,uSun;uniform float uAspect,uFov,uTime,uCloud,uCirrus;${GLSL_NOISE}${GLSL_SKY}void main(){vec2 p=vUV*2.-1.;vec3 dir=normalize(uForward+uRight*p.x*uAspect*uFov+uUp*p.y*uFov);frag=vec4(skyColor(dir),1.);}`;
const AA_FS=`#version 300 es
precision highp float;in vec2 vUV;out vec4 frag;uniform sampler2D uImage;uniform vec2 uPixel;float luma(vec3 c){return dot(c,vec3(.299,.587,.114));}void main(){vec2 uv=vUV;vec3 c=texture(uImage,uv).rgb,n=texture(uImage,uv+vec2(0,uPixel.y)).rgb,s=texture(uImage,uv-vec2(0,uPixel.y)).rgb,e=texture(uImage,uv+vec2(uPixel.x,0)).rgb,w=texture(uImage,uv-vec2(uPixel.x,0)).rgb;float lc=luma(c),ln=luma(n),ls=luma(s),le=luma(e),lw=luma(w);float hi=max(lc,max(max(ln,ls),max(le,lw))),lo=min(lc,min(min(ln,ls),min(le,lw)));vec2 dir=vec2(-(ln-ls),le-lw);dir=normalize(dir+vec2(.00001))*uPixel;vec3 a=(texture(uImage,uv+dir*.65).rgb+texture(uImage,uv-dir*.65).rgb)*.5;float edge=smoothstep(.04,.2,hi-lo);float grain=fract(sin(dot(gl_FragCoord.xy,vec2(12.9898,78.233)))*43758.5453)-.5;frag=vec4(mix(c,a,edge*.65)+grain/330.,1.);}`;
const DEPTH_VS=`#version 300 es
precision highp float;layout(location=0)in vec3 aPos;uniform mat4 uModel,uVP;void main(){gl_Position=uVP*uModel*vec4(aPos,1.);}`;
const DEPTH_FS=`#version 300 es
precision highp float;void main(){}`;
